image: Visual Studio 2019
version: 1.0.0.{build}

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

notifications:
  - provider: Webhook
    url:
      secure: RQOjbD0a6023xZNVZ7zzk7PjRpoF448yAGSM8koDLhmkmzUM5yPCgmaad8aJqIs8RUNIyviWWVKgyVoHDnXu54LGOTNVOCWgVLopKG8FA/Ofnc/R3wb8e0Y1VLME2TDc4OyE8nUxd78/lJY7qiz0pR1OZDgDregNYwczlizdDJNHSumbS17VNKQygVqdwoqd

init:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))" }

install:
  - git submodule update --init --recursive
  - nuget restore %APPVEYOR_PROJECT_NAME%.sln

build_script:
  - msbuild %APPVEYOR_PROJECT_NAME%.sln /t:Build /p:Configuration=Release

after_build:
  - 7z a %APPVEYOR_PROJECT_NAME%.7z %APPVEYOR_BUILD_FOLDER%\bin\Release\*
  - appveyor PushArtifact %APPVEYOR_PROJECT_NAME%.7z

deploy:
  - provider: GitHub
    release: v$(APPVEYOR_BUILD_VERSION)
    api_key:
      secure: "DkvKC8KRj8AipGu/oWW/J2e6jMWt2xXQfKU7oefFMsp0ZMfzz+OR9Y9XpML+ZmG4"
    artifact: /.*\.7z/
    draft: false
    prerelease: false
    on:
        branch: master
        appveyor_repo_tag: true
